<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DAAcl\Permissions\Acl'           => __DIR__ . '/src/DAAcl/Permissions/Acl.php',
    'DAAcl\Fixture\LoadRole'          => __DIR__ . '/src/DAAcl/Fixture/LoadRoles.php',
    'DAAcl\Entity\RoleInterface'      => __DIR__ . '/src/DAAcl/Entity/RoleInterface.php',
    'DAAcl\Entity\ResourceInterface'  => __DIR__ . '/src/DAAcl/Entity/ResourceInterface.php',
    'DAAcl\Entity\Privilege'          => __DIR__ . '/src/DAAcl/Entity/Privilege.php',
    'DAAcl\Entity\PrivilegeInterface' => __DIR__ . '/src/DAAcl/Entity/PrivilegeInterface.php',
    'DAAcl\Entity\Resource'           => __DIR__ . '/src/DAAcl/Entity/Resource.php',
    'DAAcl\Entity\Role'               => __DIR__ . '/src/DAAcl/Entity/Role.php',
    'DAAcl\Module'                    => __DIR__ . '/Module.php',
);
