<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DAAcl\Module'           => __DIR__ . '/Module.php',
    'DAAcl\Fixture\LoadRole' => __DIR__ . '/src/DAAcl/Fixture/LoadRoles.php',
    'DAAcl\Permissions\Acl'  => __DIR__ . '/src/DAAcl/Permissions/Acl.php',
    'DAAcl\Entity\Resource'  => __DIR__ . '/src/DAAcl/Entity/Resource.php',
    'DAAcl\Entity\Privilege' => __DIR__ . '/src/DAAcl/Entity/Privilege.php',
    'DAAcl\Entity\Role'      => __DIR__ . '/src/DAAcl/Entity/Role.php',
);
