<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DAErp\Module'                     => __DIR__ . '/Module.php',
    'DAErp\Controller\IndexController' => __DIR__ . '/src/DAErp/Controller/IndexController.php',
);
