<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DABlog\Controller\IndexController' => __DIR__ . '/src/DABlog/Controller/IndexController.php',
    'DABlog\Module'                     => __DIR__ . '/Module.php',
);
