<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DAFamilyBudget\Module'                              => __DIR__ . '/Module.php',
    'DAFamilyBudget\Controller\IndexController'          => __DIR__ . '/src/DAFamilyBudget/Controller/IndexController.php',
    'DAFamilyBudget\Controller\CategoriesRestController' => __DIR__ . '/src/DAFamilyBudget/Controller/CategoriesRestController.php',
    'DAFamilyBudget\Controller\BillingsRestController'   => __DIR__ . '/src/DAFamilyBudget/Controller/BillingsRestController.php',
    'DAFamilyBudget\Service\Billing'                     => __DIR__ . '/src/DAFamilyBudget/Service/Billing.php',
    'DAFamilyBudget\Service\Category'                    => __DIR__ . '/src/DAFamilyBudget/Service/Category.php',
    'DAFamilyBudget\Entity\Billing'                      => __DIR__ . '/src/DAFamilyBudget/Entity/Billing.php',
    'DAFamilyBudget\Entity\Category'                     => __DIR__ . '/src/DAFamilyBudget/Entity/Category.php',
    'DAFamilyBudget\Enum\BillingType'                    => __DIR__ . '/src/DAFamilyBudget/Enum/BillingType.php',
);
