<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DASite\Module'                                    => __DIR__ . '/Module.php',
    'DASite\Controller\Factory\IndexFactoryController' => __DIR__ . '/src/DASite/Controller/Factory/IndexFactoryController.php',
    'DASite\Controller\IndexController'                => __DIR__ . '/src/DASite/Controller/IndexController.php',
);
