<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DACore\Crud\AbstractCrudRestController'      => __DIR__ . '/src/DACore/Crud/AbstractCrudRestController.php',
    'DACore\Crud\ResponsesInterface'              => __DIR__ . '/src/DACore/Crud/ResponsesInterface.php',
    'DACore\Interfaces\Rest\PrepareDataInterface' => __DIR__ . '/src/DACore/Crud/PrepareDataInterface.php',
    'DACore\Crud\SerializerInterface'             => __DIR__ . '/src/DACore/Crud/SerializerInterface.php',
    'DACore\Crud\AbstractCrudService'             => __DIR__ . '/src/DACore/Crud/AbstractCrudService.php',
    'DACore\Auth\GetSetAdapterInterface'          => __DIR__ . '/src/DACore/Auth/GetSetAdapterInterface.php',
    'DACore\Auth\AbstractAuthService'             => __DIR__ . '/src/DACore/Auth/AbstractAuthService.php',
    'DACore\Auth\AbstractAdapter'                 => __DIR__ . '/src/DACore/Auth/AbstractAdapter.php',
    'DACore\Auth\AuthServiceInterface'            => __DIR__ . '/src/DACore/Auth/AuthServiceInterface.php',
    'DACore\Module'                               => __DIR__ . '/Module.php',
);
