<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DADummyTest\Module'               => __DIR__ . '/Module.php',
    'DADummyTest\Fixture\LoadGoodTags' => __DIR__ . '/src/DADummyTest/Fixture/LoadGoodTags.php',
);
