<!doctype html>
<html class="no-js">
  <head>
      <base href="/">
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title ng-bind="pageTitle"></title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width">

      <link rel="stylesheet" href="blog/css/main.css">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.0/imagesloaded.pkgd.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.1.0/masonry.pkgd.min.js"></script>



  </head>
  <body>
    [LAYOUT SITE 01]
    <a ui-sref="Home">Home</a>
    <a ui-sref="Teste">Test View</a>

    <div ui-view></div>
    <script src="blog/js/main.js"></script>
  </body>
</html>
