<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DABase\Types\EnumType'                => __DIR__ . '/src/DABase/Types/EnumType.php',
    'DABase\Entity\SocialNetwork'          => __DIR__ . '/src/DABase/Entity/SocialNetwork.php',
    'DABase\Entity\Person'                 => __DIR__ . '/src/DABase/Entity/Person.php',
    'DABase\Entity\Images'                 => __DIR__ . '/src/DABase/Entity/Image.php',
    'DABase\Entity\ImageInterface'         => __DIR__ . '/src/DABase/Entity/ImageInterface.php',
    'DABase\Entity\SocialNetworkInterface' => __DIR__ . '/src/DABase/Entity/SocialNetworkInterface.php',
    'DABase\Entity\PersonInterface'        => __DIR__ . '/src/DABase/Entity/PersonInterface.php',
    'DABase\Enum\EnumGenderType'           => __DIR__ . '/src/DABase/Enum/EnumGenderType.php',
    'DABase\Enum\EnumImageType'            => __DIR__ . '/src/DABase/Enum/EnumImageType.php',
    'DABase\Enum\EnumSocialType'           => __DIR__ . '/src/DABase/Enum/EnumSocialType.php',
    'DABase\Module'                        => __DIR__ . '/Module.php',
);
