<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DAAdmin\Controller\IndexController' => __DIR__ . '/src/DAAdmin/Controller/IndexController.php',
    'DAAdmin\Module'                     => __DIR__ . '/Module.php',
);
