<!doctype html>
<html class="no-js">
  <head>
    <base href="/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title ng-bind="pageTitle"></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="base/css/base.css">
    <link rel="stylesheet" href="erp/css/main.css">
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body ng-controller="LayoutController as layout" ng-cloak>
    <div id="loading-bar-container"></div>

    <div class="off-canvas-wrapper">
        <div class="off-canvas-wrapper-inner">
            <nav id="da-admin-top-menu">
                <div class="title-bar">
                    <div class="title-bar-left">
                        <div id="da-admin-layout-header" data-ui-view="header"></div>
                    </div>
                </div>
            </nav>
            <div class="off-canvas position-left">
                <div id="da-admin-layout-leftsidebar" data-ui-view="leftsidebar"></div>
            </div>
            <div class="off-canvas-content">
                <div class="breadcrumbs" ncy-breadcrumb></div>
                <div id="da-admin-layout-middlecontent" data-ui-view="middlecontent"></div>
                <div id="da-admin-layout-footer" data-ui-view="footer"></div>
            </div>
        </div>
    </div>

    <script src="erp/js/main.js"></script>

  </body>
</html>