<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DAUser\Service\Auth'                  => __DIR__ . '/src/DAUser/Service/Auth.php',
    'DAUser\Controller\AuthRestController' => __DIR__ . '/src/DAUser/Controller/UserUniqueRestController.php',
    'DAUser\Auth\Adapter'                  => __DIR__ . '/src/DAUser/Auth/Adapter.php',
    'DAUser\Entity\User'                   => __DIR__ . '/src/DAUser/Entity/User.php',
    'DAUser\Entity\UserInterface'          => __DIR__ . '/src/DAUser/Entity/UserInterface.php',
    'DAUser\Module'                        => __DIR__ . '/Module.php',
);
